const PORT = process.env.PORT || 3000;
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const MongoClient = require('mongodb').MongoClient
var https = require('https');
var db, collection;

const url = "mongodb+srv://shawn:shawnpassword@cluster0.ml67f.mongodb.net/demo?retryWrites=true&w=majority";
const dbName = "demo";



app.listen(3000, () => {
    MongoClient.connect(url, { useNewUrlParser: true, useUnifiedTopology: true }, (error, client) => {
        if(error) {
            throw error;
        }
        db = client.db(dbName);
        console.log("Connected to `" + dbName + "`!");
    });
});

app.set('view engine', 'ejs')
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())
app.use(express.static('public'))

app.get('/', (req, res) => {
  res.render('index.ejs')
})

//=============================Horoscopes==================================//
let zodiac = [
  [
    "Ravenclaws born under the sign of Capricorn excel at their studies, because they have both a love of knowledge for its own sake and a deep desire to use that knowledge to gain prestige or authority. They are disciplined students with acute perception and shrewd minds; they might take a little longer to reach conclusions than their peers, but their conclusions tend to be more well thought out and thorough. They have dry, ironic wit and are fond of making subtle jokes that only those blessed with intelligence and perception can understand. There's not much that these wizards miss; they usually know what is going on long before anybody else does.",
    "The stereotypical geeks of the magical world, Ravenclaw Aquarians are noted mostly for their genius. They are gifted theorists and inventors, and highly talented students. Most wind up doing pure research after graduating from Hogwarts. Their noses are always in books of esoteric lore. Some people may laugh at them, either for their unconventional lifestyles or (more commonly) because they are obvious nerds, but they don't care. While they can have sharp tempers, especially when they encounter ignorance or stupidity, these wizards generally mean well, and have a 'live and let live' philosophy. Their wit is legendary; not everybody gets the Ravenclaw Aquarian's jokes, but those who are subtle and intelligent enough find conversation with an Aquarian Ravenclaw to be quite funny, in a satirical and ironic and irreverent sort of way.",
    "Ravenclaw Pisceans spend so much time dreaming or reading books of legends that it's a wonder they ever come down to earth. Care must be taken that they do not neglect their material needs, including those that involve sleep, food, and drink. These wizards are natural seers, and often specialize in things like horary astrology, cartomancy, dream interpretation, oracles, and the summoning of visions. Because they possess both intellectual acumen and emotional awareness, they are capable of great insight. They are quiet students, not always the best in their classes, but tend to be brilliant at subjects which they are personally interested in. Shy and nervous, they are easily bullied or intimidated, and need some looking after by more assertive students.",
    "These Ravenclaws will have lightning-fast mental reflexes. Aries is an intellectual sign, but it is also an impatient sign; Ravenclaws who were born under this sign are likely to tolerate no dull wits or stupidity, whether they see this lack of mental competence in themselves (in which case they will berate themselves for not understanding, or give up quickly in frustration without really trying to overcome their difficulty in learning) or in others (in which case they will lash out at the offender with acidic comments and haughty, cutting looks). These Ravenclaws will want to be at the head of the class, dominating other students in their chosen intellectual field, and may be almost as competitive as Slytherins. However, the true aim of every Ravenclaw is knowledge, knowledge, and more knowledge. While a Slytherin might see losing a magical duel or being bested by another student in a DADA class as humiliating, the Ravenclaw will probably just take delight in competition for its own sake, and see defeat as a learning experience.",
    "In some ways, this seems almost a contradiction. A head-in-the-clouds, theoretically-oriented Ravenclaw, born under the pragmatic, materialistic sign of Taurus? However, a surprising number of philosophers (including Socrates) have been Taureans. The intellectual Taurus is gifted not only with prodigious mental capacity, but also the sensible logic, determination, and assurance to see a theorem through from start to finish. Ravenclaws born under this sign make excellent magical researchers and are gifted with the unusual capacity to write sensibly and fluently about their results and interpretations of experiments. Because Taurus is a patient sign, and good at communication, many Ravenclaw Taureans eventually end up teaching at Hogwarts.",
    "Ravenclaw Geminis are geniuses of communication. They debate ideas, write brilliant treatises, teach exciting classes, read large numbers of books on a regular basis, and study arcane languages. Because Mercury the planet is associated with the alchemical substance of quicksilver, the god Hermes (the messenger of the gods, and the conductor or dead souls to the Underworld), and the historical founder of alchemy, Hermes Trismagistus, many Ravenclaw Geminis also excel at the study of alchemy. These Ravenclaws are some of the best and most brilliant of their class, but they need to learn to finish the projects they start, and to differentiate between what is viable and what is best left as a 'really great idea.'",
    "This is an odd sign for Ravenclaw wizards to be born under, but it happens. You'll see them wandering the halls, muttering to themselves or lost in daydreams. Some great Ravenclaw astrologers have been born under this sign. Any magic which involves moonlight and intricate calculations, actually, will attract the Ravenclaw Cancer. They may also be prone to collecting and enchanting white stones that remind them of the moon - pearls, moonstones, opals... These wizards have an extremely dry sense of humour, and are prone to making trenchant observations of the world around them.",
    "Ravenclaw Leos are brilliant scholars, loudly adding to classroom discussions and impressing others with the breadth, if not depth, of their knowledge. Many find themselves attracted, as well, to positions on the Quidditch team, partly because this lets them use their abundant energy, partly because it allows them to hog the limelight for a few hours while everybody in their House cheers them on. Their optimism and charisma make them friends everywhere, regardless of House affiliation, and their creativity makes them highly inventive in the laboratory. On the other hand, they are prone to fat egos and intellectual arrogance, and this can be intensely annoying. Emotional maturity will eventually teach them that they don't know everything, and sometimes it's best to let other people speak up and take the credit.",
    "Ravenclaw Virgos are skeptical, analytical, mathematically oriented, and sharp witted. Many become great magi, alchemists, and astrologers. These people love ideas and theoretical discussion, and their leaps of intuition can be uncanny. The Earth element makes them shrewd and pragmatic, and keeps them from flying off into cloudcuckooland.",
    "All Ravenclaws are intellectual, but Ravenclaw Libras have their heads in the clouds more than most (Pisces Ravenclaws may have them beat, but not by much). They are romantic and idealistic, and prefer to live in the world of pure theory rather than in the messy world of action. While social and pleasant, they are still quiet and shy, and rarely make the first move when in a group of people. In the classroom, they tend to wait to be called on, or raise their hands when they are sure that no one else knows the answer, but they do tend to be the teacher's pet on a fairly regular basis. It's hard to hate them for this, because they are so pleasant to everybody. Ravenclaw Libras are the most speculative (and indecisive) of all Libras, because they have the intellectual capacity to explore all ramifications of every action and reaction.",
    "Curiosity killed the cat; satisfaction brought it back. If ever a wizard exhibited a danger of self destruction from too much knowledge, surely it was a Ravenclaw Scorpio. It doesn't matter whether the pet obsession this week is botany, Muggle pop music, or the history of the Necronomicon, if a Ravenclaw Scorpio wants to know about it, then he will, and damn the consequences: full speed ahead. Indeed, just mention that a subject is 'forbidden' and you'll see a peculiar light shine in their eyes. They sneak into locked rooms after dark, and forge passes to the restricted library sections. The lust for arcane knowledge is both the greatest strength of these wizards, and the Achilles heel. It's best to indulge them whenever possible and let the obsession burn itself out; and, when this is not possible, to explain in great detail and absolutely *no* patronizing why the subject must not be explored. These Ravenclaws are quiet and secretive, but don't be fooled by that calm and placid exterior; they have hidden depths.",
    "Ravenclaw Sagittarians are the philosophers of the magical world. They love pure theory, pure mathematics, and anything that appeals to their yearning for far horizons, whether those horizons be physical (in which case they will do a lot of traveling) or mental. They excel at astrology and research, and have the rare gift of both being able to investigate a subject deeply and then being able to explain it to other people in plain language. This makes for excellent teaching potential. They are cheerful, athletic, brisk, and humourous, and also decidedly eccentric. Sometimes they get on people's nerves, because they don't have as many interpersonal skills as they seem to think they have, but it's hard to stay mad at a Ravenclaw Sagittarian for very long. They're just too goofy."
  ],
  [
    "Hufflepuff Capricorns are extraordinarily hard workers. Their sense of duty is strong, and they have enough discipline to manage not just themselves, but a whole army of people if needs be. They take joy in being useful to other people, so are often quite helpful whether as lab partners or in their chosen careers (often in the Ministry of Magic). However, because they also make good leaders and want to get ahead in the world due to having more ambition than the average Hufflepuff, they tend to get selected for positions of authority, where they soon make themselves indispensable. They're good at organizing things. Hogwarts should always have a Hufflepuff Capricorn somewhere on the administration, to make sure all affairs are actually in order (all those head-in-the-clouds creative types on the faculty; good heavens, where would Hogwarts be if there was no way of balancing them with down to earth perspective?)",
    "Aquarians who are sorted into House Hufflepuff are introverted, but not shy; march to the beat of a different drummer, but don't wear their weirdness like a flag; socially minded, but highly critical of society. Confused? So are the Hufflepuff Aquarians, but they tend to sort things out eventually. Their minds lean toward the practical side of things - they'd rather invent new and useful spells or gadgets than dwell for hours in hot air theory - and the solutions they find to common problems are brilliantly on target. They like people and want to get along well with everybody, but are uncomfortable with intimacy; so they have lots of acquaintances but few close friends. They have the ability to laugh at most any situation.",
    "Community service? Of course, what else is magic for? Hufflepuff Pisceans live to please. They literally feel pain when other people feel pain, so often wind up doing intensive study of healing magics. Potions come naturally, too, for Pisces is a water sign, and all wizards born under water signs have some talent at potions. The temptation to make love potions and mood altering substances is very great, for Pisces is in love with love, and almost as much in love with easy escapes into altered states of consciousness. Hufflepuff Pisceans have somewhat less of a work ethic than average, but will apply themselves to their studies in the hopes that what they learn will benefit humanity somehow. They are followers, not leaders, but they do make good teachers, for they are very patient and have a gift for making subjects seem interesting to learn.",
    "Hufflepuff Ariens have an extreme abundance of energy; however, the usual Hufflepuff tendency to work hard out of duty is modified by the Aries tendency to value play over work. Therefore, expect long periods of playfulness and seeming indolence punctuated by brief, manic bursts of industry. These Hufflepuffs may also be more ambitious and socially aggressive than average, making them clear leaders in their House. Their emotional warmth, open hearts, madcap sense of humour, and quirky independence will endear them to many people, but their naivete makes for easy exploitation by more ruthless sorts of people.",
    "Taurus, the nature-loving bull, is a natural sign for Hufflepuffs to be born under. These wizards tend to specialize in herbs and nature spells, also in the husbandry and preservation of magical beasts. Their gentle good natures, open friendliness, hard work, patience, and politeness endear them to most everyone they meet. However, these Hufflepuff Taureans must be careful not to overwork themselves, lest they suffer breakdowns in health. (It has been noticed that Hufflepuffs born under the sign of Taurus swing wildly between overwork and indolence, the lazy periods being used to recharge their energy; they seem to have a problem pacing themselves.) They like their magical workrooms neat and tidy, and prefer peaceful occupations to dangerous or aggressive ones; most Hufflepuffs born under this sign wind up working as hedge witches, village herbalists, and midwives.",
    "Hufflepuff Geminis stand out for being geniuses as what Muggles like to call 'multitasking.' They can't just work on one project - they need to have eight or nine things going all at once, usually as close to a deadline as possible. They also tend to be a little more outspoken and extraverted in the classroom than the average Hufflepuff, who would rather sit near the back of the classroom and quietly take notes to study later. Because they bite off more than they can chew, they are always complaining of various ailments related to stress.",
    "Hufflepuff Cancers are oriented first and foremost to the home and to all things domestic. The ultimate homebodies of the magical world, they are at their happiest when they are puttering in the kitchen, stirring up food in magical cauldrons or whipping up soothing, healing potions. These wizards desperately need to be needed. If cut off from family, a circle of close friends, or a flock of wounded birds to tend, they will get anxious and depressed, unless their energies are directed somehow to a cause or a person which finds them good use. They are caring and compassionate, and are excellent listeners.",
    "Although this might seem like a strange sign for Hufflepuffs, Hufflepuff Leos do exist. Many become the prefects of their House when they reach the proper age, for they are good with other people, have a fine sense of initiative, and have the nobility of spirit to see that the right thing gets done at all times. They like to set a good example for others - the phrase 'noblesse oblige' probably sums it up well (nobility imposes obligation). Generous to a fault, they will give everything they have (be it money, energy, or loyalty) to anyone who needs it.",
    "Hufflepuff Virgos are incredibly hard workers and bright, if quiet, students. They excel at any magical arts related to domestic life or healing. They must be watched carefully to ensure that they do not overstress their systems by performing too much work; these wizards have a very hard time learning the meaning of the word 'no', and are thus easily taken advantage of for their work ethic. Let other people do the leading and the decision making; they are content to serve. And on their backs rests the industry of the world. Without people like them, civilization might grind to a halt, for who would take care of the practical details?",
    "Libras sorted into House Hufflepuff are some of the sweetest, most charming individuals you will ever meet. They work hard at their studies compared to other Libras (most Libras would rather coast on their strengths than apply themselves to all their subjects) and are often quite successful. Physically, however, they remain unathletic and lazy - the closest they'll ever get to a Quidditch match is the spectator's box, and that only if the weather is pleasant. Anything beautiful and harmonious appeals to the Hufflepuff Libra. Since potions and alchemy require an instinctive awareness of the harmony of ingredients, Hufflepuffs who are Libras display a surprising facility in these subjects. These wizards live to help other people, and to help their friends get along with each other; nothing hurts them more than to see people in distress or bickering with each other. Feuds and wars between wizards distress them. Equally distressing is the disharmony between Muggles and magic users. Many Hufflepuff Libras become Muggle specialists, hoping to bridge the gap between magical and non-magical.",
    "This is one of the more bizarre signs to get sorted into House Hufflepuff, but every now and then it happens. It's not as contradictory as one would think. Scorpio is perfectly happy to work behind the scenes without getting much recognition, provided that work actually gets something meaningful done and results in personal success; success means different things to different people, and Hufflepuff Scorpios tend to define success as 'accomplishment' rather than as 'prestige.' These Hufflepuffs are indefatigable. They have the energy and the willpower to keep going even when everyone else around them has quit. They are workaholics to an extreme, if they are obsessed with a particular project; otherwise, they are happy to devote their prodigious energies to their family and friends, to whom they are devoted. Scorpio is often associated with the serpents of Aesculapius, demi-god of medicine, and the social orientation and skill at herbals that Hufflepuff wizards exhibit make the Scorpio Hufflepuff a natural healer.",
    "Hufflepuff Sagittarians are good-natured, cheerful, and clever, and their natural skill at teaching other people what they have learned ensures that they will be professors or magical tutors upon leaving Hogwarts. Their outdoorsy ways also give them a gift with all growing things and wildlife. These wizards have more difficulty than most wizards of their house applying themselves to their studies; Sagittarius is a sign of intellect, but not discipline, and it is painful for Hufflepuffs born under this sign to do homework when they'd rather be out on the Quidditch field or taking nature hikes. They will knuckle down, but not without protest. Although they are socially graceless, their good natures make up for any accidental offenses they may commit."
  ],
  [
    "While not the most common sign for Gryffindors to be born under, the combination of Gryffindor aims with Capricorn traits results in wizards who are exceptionally well balanced. For once, here are Gryffindors who will not go charging off on quests without first making thorough preparations and arranging for backup. They are resourceful, well grounded, and self confident, hard workers, and extremely reliable. You can always trust a Gryffindor Capricorn's word; they will not only mean it when they say they will do something, they will follow through successfully. House Prefects often come from this sign, because they are responsible, good students, and natural leaders. What many people forget about the Capricorn is that although they are part goat, they are also part mermaid. That mermaid half represents all the fanciful dreams and lofty ambitions that the quiet Capricorn often hides beneath an unassuming surface. Perhaps Capricorns are sorted into this House because the House needs balance, but those hidden dreams and whimsies probably have a lot to do with it, too.",
    "Gryffindor Aquarians are the social activists and loons of their House. They'll picket for House Elf Liberation. They'll wear their robes inside out because they spent all night reading, not pay attention to how they dressed the next day, and not care if their rumpled appearance is pointed out to them. They are intellectual rebels and will loudly defend their opinions, even if doing so makes enemies. They are apt to question authority. 'Even Merlin was wrong, some of the time,'' they'll say, shrugging. While not particularly good at dealing with crisis situations (they stress out easily) they do tend to have enough foresight to see the situations coming, and prevent them from happening in the first place. They can be flamboyantly talented, but are less interested in using their talent to 'make it big' than in using it to make a better life for themselves or other people. Because Gryffindor tends to be a flamboyant house, these oddballs (they are always odd) tend to stick out for being unusual.",
    "While not the bravest of Gryffindors, the Gryffindor Pisces still exhibits a quiet courage. They aren't afraid to face painful truths, if there really is no way of escaping them. These Gryffindors are deeply compassionate, and full of emotional strength, often becoming the unofficial counselors in the common room who everybody runs to for advice. They are romantic to an extreme; their minds are stuffed full of fairy tales, myths, and legends. They often spend more time daydreaming than doing their homework, to the vexation of their professors. Still, their daydreams do sometimes produce uncanny insights.",
    "The Gryffindor Aries is extremely idealistic, and has a tendency to fight hard for many causes - the more lost, the better. Gryffindors born under this sign will also have very short fuses, and can be expected to fight regularly with other students, over ethical questions or over anything else that makes a good excuse. Since Mars is a planet that encourages war games and competition and bursts of hard physical activity, there may be many Quidditch players born under these aspects. A Gryffindor Aries is an open book; a truth potion would never be needed on one, because they are hopelessly honest and open. These wizards will display uncanny charisma and leadership ability, and will be among the most popular within their class.",
    "These wizards will be less hot headed and apt to charge at windmills than other Gryffindors, for Taurus is an earth sign, and the element of Earth adds a pragmatic streak to even the flightiest of wizards. As with all Taureans, though, if a Gryffindor Taurus is pushed hard enough, she will exhibit a volcanic temper. Gryffindors born under this sign will be exceptionally loyal to their friends, and will have high standards of personal integrity.",
    "You'll need track shoes to keep up with these Geminis. They have so much energy that they exhaust nearly everyone, save other Gryffindor Geminis. In class, they love to get into debates with the professor. Out of class, they love to get into trouble. These Gryffindor Geminis are as easily stirred by romantic dreams and noble causes as any other Gryffindors, although their involvement is more mental than practical - they lack the fortitude for battle and are best left passing propaganda to the real warriors. Expect a large number of them to work for the Daily Prophet after graduation.",
    "Gryffindors born under the sign of Cancer will root for the home team until their throats are raw. They are deeply loyal to their House (and also to any friends outside of their House, although these may take a back seat to Gryffindor loyalties). Make a friend with a Gryffindor Cancer, and you've made a friend for life. Cancer is a sentimental, yet high achieving sign that dreams often, and dreams big; this combined with the Gryffindor romantic streak creates a quixotic, almost anachronistically chivalrous temperament.",
    "This is a natural sign for Gryffindors, not least because the griffin is part lion. Gryffindors born under this sign are outgoing, friendly, affectionate, and likeable. They make friends easily and are crushed when their advances are rejected. Their romantic, chivalrous nature makes them perfect examples of all that is best in their House. However, they are also bossy, domineering, spendthrift, and overly dramatic (ever heard the phrase 'drama queen?') They have sharp tempers and need to learn to direct their anger toward only needful causes. The natural creativity and flamboyance of Leo makes Gryffindors born under this sign good at most everything they attempt, provided they apply themselves to learning magic rather than using magic to hog the limelight.",
    "This is not a natural sign for Gryffindor, but some Gryffindors do end up born under the influence of Virgo. They are hard workers and usually very bright; they tend to be more ethically obsessed than most. Some Virgo wizards are also sorted into House Gryffindor because of their amazing imaginations; on the surface they may appear straight-laced and almost nervous, but inside is a wealth of romantic yearning and fantastic excitement. They quietly build dream castles in their minds; and the practical influence of the Earth element means that they, unlike more flighty signs, may have some chance of building those dream castles on solid foundations.",
    "Gryffindor Libras will be a little bit more circumspect than other members of their House; the Gryffindor tendency to act first and think second will be moderated by the Libra tendency to weigh all options carefully before making a decision. Emphasized to an extreme will be the Gryffindor obsession with justice. Libras are the natural judges, lawyers, and police of the Zodiac, often more concerned with what is fair and just for all than what is merciful for the few. Expect a Gryffindor born under this sign to be an outspoken defender of underdogs, and to stand up for their beliefs more vociferously than the average Libra (Libras are usually too polite to say something that might risk offending other people). All Libras have the potential to become Aurors, because of the strong drive for justice, but the Gryffindor courage makes people of this sun sign who were sorted into this House more likely to become Aurors than people of other signs and Houses.",
    "Expect stamina, incredible courage, intense and stormy emotions, burning idealism, and indomitable will. Gryffindor Scorpios are never drawn in shades of pastel; they are always blood red and mesmerizing gold. There are few followers born under these aspects; Scorpios born into this house tend to be either leaders or loners. They are well placed on the Quidditch field, where their natural competitive streak and their great store of personal energy make them natural Beaters (or, really, naturals at any position on the field). Expect them to get into frequent duels, and expect them to gravitate naturally to DADA, for all Scorpios are fascinated by anything dark and forbidden, and Gryffindor Scorpios will want to take their place as defenders as early in their careers as possible. Expect passion. Expect wisdom. But don't expect a lot of time to take a breather. Many people born under this aspect also end up as Aurors; they're the perfect 'bad cops' to the 'good cop' Libra wizards.",
    "Gryffindors born under this sign are exuberant and full of good humour. They are intelligent, but often do not make the best of students, because they would rather be outside enjoying the fresh air or off studying on their own. They aren't good at diplomatic silence; if a teacher makes a mistake, the Gryffindor Sag will draw attention to it right away, usually loudly and in front of the entire class. At length. These students can get into trouble - their hot tempers make for easy dueling matches, and their impish senses of humour inspire a great many practical jokes. Still, they rarely mean anything malicious. They're too jovial to harbour malice. These Gryffindors are likeable extraverts, on good terms with practically everybody, and they generally do all right in the end. Many excellent Quidditch players come from this sign."
  ],
  [
    "The traits emphasized here will be ambition, determination, discipline, and pragmatism. You can't make that castle in the sky if you don't build a solid foundation under it, and Capricorns excel at building foundations. (Actually, they excel at planning the foundations and directing others to do the grunt labour. It's not that they're afraid to get their hands dirty, but large work usually requires delegation and a staff, and Capricorns are managers more often than not.) While not flamboyant or showy about it, Capricorns still tend to be obsessive overachievers, a common trait in House Slytherin. Too, wizards born under the sign of Capricorn are good at being discreet, secretive, and diplomatic; whereas the Libra's diplomacy is based on charm and a desire for harmony, the Capricorn's diplomacy is based on the knowledge that being on good terms with people is extremely useful in getting one's way or finding out sensitive information. These also are traits commonly associated with House Slytherin. They might not be sexy traits, but they're very handy.",
    "Slytherin Aquarians are lucky. They have inner drive, determination, and great ambition; they also have brilliance, cleverness, and an almost total disregard for 'what everybody thinks,' which means they can go for their dreams without caring if other people mock them or consider them strange. More introverted and full of social conscience than the average Slytherin, these wizards are easily overlooked socially (by fools), although they excel in the classroom and eventually become great wizards indeed. They are stubborn and will not back down without a fight if challenged.",
    "This is not the most natural of sun signs for a Slytherin to be born into, but it's not unheard of, and when it happens, the results are usually interesting. These Slytherins dream big. Because of their romantic streak and their need for mystery and glamour, their dreams are often the most dazzling of all. To put them into fruition, they either need to develop a pragmatic streak, or partner up with a practical wizard who will help midwife the dreams and keep them going. These Slytherins are loners or followers rather than leaders, but don't assume that they are doormats - they wouldn't be Slytherin if they didn't have some backbone. They will accomodate people to the best of their limits, but if those limits are pushed or violated, they will get angry - and they will remember. A Pisces never forgets a cut or a kindness. Ever. Slytherin Pisceans often delve into mysteries involving death and afterlife, for Pisces is naturally placed in the house of endings; Pisces wizards in House Slytherin will also be brilliant seers and potion brewers. Because these wizards are good with people and human psychology, they understand everybody around them; and because they are so quiet and unassuming, nobody notices that they are there. The wise Pisces in House Slytherin of course is aware of this, and uses it to advantage.",
    "A Slytherin Aries is a bundle of contradictions. In some ways, they have the potential to be the strongest of their House - the intensity, drive, and brilliant visionary dreams of the Aries combined with the innate leadership skills, the charisma, and the profound sense of self (including the eccentric lack of interest in conforming to what other people think) is stuff of which great magical legends are made. However, a Slytherin Aries has much to learn about politics, knowing who is an appropriate object of trust and who is not trustworthy, knowing when to keep one's mouth shut, and knowing when to avoid acting on impulse in order to use a situation to its best advantage. Although they hate to admit it, these Slytherins are easily manipulated by more cynical, shrewd peers in the Serpent's Den. If they can learn to manage their blind spots, they will go far. Slytherin Aries types can be quite cruel, especially if they have enough physical prowess to bully smaller students; those that are not cruel can still be thoughtless and brutally tactless without actually meaning to cause damage.",
    "In this House, the traits associated with Taurus that will be most emphasized are materialism and loyalty. These Slytherins will be almost blindly loyal to their friends and allies, and they will value wealth and the trappings of wealth over more intangible assets. Determination will also be emphasized. All Slytherins are determined, but the stubborn Taurus Slytherin is unstoppable once they have their mind set on something. A large number of Slytheirns in this sign work for Gringotts after graduating from Hogwarts, for they are very good with money.",
    "Ever heard the phrase 'snake-tongued?' It must have been invented to describe a Slytherin Gemini. (This doesn't refer to the Parseltongue gift, either, although the few Slytherin wizards who exhibited it have had a disproportionate number of Geminis in their midst.) Slytherin Geminis have the dubious gift of being able to lay the blarney on thick, and be believed. This is due to both their imaginative mental agility and to their skill with words. Of course, not all Slytherin Geminis are liars - but it is probably advisable to get all sides of the story if you hear interesting gossip from one of these wizards. Slytherins born under the sign of Gemini are also naturally skilled at any magical work which involves sleight of hand or incantations. They are less determined and aggressive than the average Slytherin, though, save perhaps in a field that involves debate. You will find far more of them chatting in the common room or looking up arcane lore in the library than on the Quidditch field or in a dueling match, with the exception of Quidditch Seekers: the sharp eyesight and quick reflexes associated with Gemini are good traits for a Seeker to have.",
    "Potions, potions, and more potions. Any Slytherin born under a water sign will excel at potions, and the Cancer Slytherin is no exception. The leadership ability and the lofty dreams of Cancer will also be emphasized; as will loyalty (directed for the most part to one's House). Slytherins born under the sign of Cancer will be more hard-shelled and less sentimental than other Cancers, but don't be fooled by their bossy, efficient exteriors. On the inside they are soft and needy, and they learn from a young age to hide this well. Slytherins born under water signs have another thing in common with each other: keen insight into what makes other people tick. These Slytherins are good at manipulating other people's emotions, and good as well at quickly learning the hidden stories behind the otherwise inexplicable actions of acquaintances. They never forget a cut or a kindness, so it is best to stay on their good side unless you want an obsessive, vindictive enemy.",
    "Slytherin Leos can be either very good, or very bad. At their best, they exemplify all that 'nobility' is made of: confidence, openness, charm, initiative, generosity of spirit, wisdom, judgment, and poise. At their worst, they become elitist, bullying bigots. How they end up depends on the company they keep, and how they are encouraged to act early in life. Either way, they never lack attention - it's hard to ignore a Slytherin born under this sign. These Slytherins usually end up in positions of responsibility and leadership, because of their charisma and natural ability. Their creativity and drive also makes them very resourceful.",
    "While these Slytherins might not be the most outgoing of their class, they are often among the most wise, and their canny observation and lightning-fast analysis of any given situation will take them far. Often behind that quiet mien hides the mind of a big dreamer, who had both the imagination to come up with a concept and the power to follow it through. These Slytherins are an interesting mix of politeness and politics, pragmatism and intuition. They make good alchemists, Ministry bureaucrats (well, somebody's got to do it), and academic advisors. They are often underestimated. This is most unwise.",
    "This combination of sun sign and House ought to be nicknamed 'The Magical Corps of Diplomats.' Slytherins born under this sign are poised, polished, suave, well read, well bred, and excruciatingly polite and correct in everything they do - the perfect gentry of the magical world. Never a bully or a bravo here! No, these Slytherins would say 'I despise you and think your are worthless scum' and make it sound like 'How do I love thee? Let me count the ways...' They are discreet, sympathetic, easy to talk to, and know how to put people at ease. This can, of course, be a wonderful asset in espionage (the flip side of diplomacy!) and these Slytherins are more than capable of hiding their true feelings in order to get information or befriend a rival. Because they need to act in partnership with others and hate to be alone, they are rarely decision makers, and must be careful who they seek to befriend, lest they be led astray into the wrong crowd. Slytherin Libras also ought to marry into money if they don't have much of their own, for their love of luxury and culture can make for extremely high maintenance expenses.",
    "What is said of Slytherins born under all other signs is doubly true of Slytherins born under Scorpio. (Or was it that what is said of Scorpios is doubly true of Scorpios sorted into Slytherin?) There is no middle ground here - these wizards can embody all that is the very best in the world... or all that is the very worst. They are heroes, or they are villains. They are attracted to the dark, twisted, and forbidden mysteries of the world from the day they are born, and only they can determine whether they will study the dark arts in order to oppose them, or to embrace them. However, as Scorpio is a sign of transformation and regeneration, it is not impossible for even the most evil of dark wizards to turn to the path of good... Scorpio Slytherins have uncanny wisdom, insight into human psychology, and high 'emotional IQ's.' They are incredibly ambitious, often exist in a state of total ego, and if misused or hurt, can nurse the wound and seethe for decades. Still, although they are often tempted to do horrible things in the name of glory or discovery, they nevertheless are often the kindest, most compassionate, and most forgiving people of all, for they have seen their own inner darkness, faced it, and do not run from it when they encounter it in others.",
    "Yes, Virginia, Sagittarians can get sorted into House Slytherin. And not always as Quidditch players, either, although there have been jokes made about how the Hat will sort big, tall Sags into Slytherin just to pad out the team. Slytherin Sagittarians are sorted primarily because of their ability to dream; these Sags have a vision, and with the support of their House, can channel their energies to great achievements. In return they give their House something priceless beyond rubies: a sense of perspective. Temporary failure is not humiliating to the Sagittarius Slytherin, merely a temporary setback in pursuit of a goal. They can laugh at themselves even when other people are laughing at them, and of course that turns the joke on the idiots who came up with it in the first place. (How devious.) Although bright, these Slytherins will coast through their classes if they can get away with it; they'd rather envision the future than attend to the details of the present."
  ]
];

let house = [
  "Welcome, RavenClaw",
  "Welcome, HufflePuff",
  "Welcome, Gryffindor",
  "Welcome, Slytherin"
];

let answers = [];

app.put('/horoscope', (req, res) => {
  console.log(req.body)
  answers.push([house[req.body.house],zodiac[req.body.house][req.body.sign]])
  answers.reverse()
  console.log(answers)
let data = {message: {'house':answers[0][0],
'sign': answers[0][1]}}

app.get('/zodiac', (req, res) => {
    res.render('zodiacs.ejs', data)
  })

})

app.get('/zodiac', (req, res) => {
  let data = {message: {'house':answers[0][0],
  'sign': answers[0][1]}}
    res.render('zodiacs.ejs', data)
  })

// app.put('/horoscope2', (req, res) => {
//   console.log(req.body)
//   answers.push([house[req.body.house],zodiac[req.body.house][req.body.sign]])
//   answers.reverse()
//   console.log(answers)
// let data = {message: {'house':answers[0][0],
// 'sign': answers[0][1]}}
//
// app.get('/', (req, res) => {
//     res.render('index.ejs', data)
//   })
//
// })
